{% set name = "scanning_drift_corr" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3506995a12a692235861f4c422a3fc57af15a629c4ebddf75ad6cc3bc1d27f80

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - matplotlib-base
    - scipy
    - tqdm
    - h5py

test:
  imports:
    - scanning_drift_corr.api
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ptim0626/scanning-drift-corr
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Correct scan drift distortion
  description: |
    This package corrects scan distortion by using orthogonal pairs.
  dev_url: https://github.com/ptim0626/scanning-drift-corr

extra:
  recipe-maintainers:
    - ptim0626
